// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/realHoangHai/awesome/config"
	"github.com/realHoangHai/awesome/internal/biz"
	"github.com/realHoangHai/awesome/internal/service"
	"github.com/realHoangHai/awesome/internal/storage"
)

// Injectors from wire.go:

// wireApp init awesome application
func wireApp(cfg *config.Config) (*service.UserService, func(), error) {
	client := repo.NewEntClient(cfg)
	cmdable := repo.NewRedisCmd(cfg)
	store, cleanup, err := repo.NewStore(client, cmdable)
	if err != nil {
		return nil, nil, err
	}
	userRepo := repo.NewUserRepo(store)
	userBiz := biz.NewUserBiz(userRepo)
	addressRepo := repo.NewAddressRepo(store)
	addressBiz := biz.NewAddressBiz(addressRepo)
	cardRepo := repo.NewCardRepo(store)
	cardBiz := biz.NewCardBiz(cardRepo)
	userService := service.NewUserService(userBiz, addressBiz, cardBiz)
	return userService, func() {
		cleanup()
	}, nil
}
